/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:11:40 PM
 */

package com.zj198.dao;


import com.zj198.model.MchBank;

public interface MchBankDAO extends BaseDAO<MchBank, Integer> {
}
