/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 27, 2012  9:40:30 AM
 */

package com.zj198.dao.hibernate;


import com.zj198.dao.MchBankDAO;
import com.zj198.model.MchBank;

public class MchBankDAOImpl extends HibernateDAO<MchBank, Integer> implements MchBankDAO {

	
}
