/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:14:03 PM
 */

package com.zj198.dao.hibernate;

import com.zj198.dao.DicServiceTypeDAO;
import com.zj198.model.DicServiceType;

public class DicServiceTypeDAOImpl extends HibernateDAO<DicServiceType, Integer> implements DicServiceTypeDAO {

}
