/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:10:50 PM
 */

package com.zj198.dao;

import com.zj198.model.MchType;

public interface MchTypeDAO extends BaseDAO<MchType, Integer> {

}
