/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:08:45 PM
 */

package com.zj198.dao;

import java.util.Date;
import java.util.List;

import com.zj198.model.PrdServiceItem;
import com.zj198.util.Pager;

public interface PrdServiceItemDAO extends BaseDAO<PrdServiceItem, Integer> {
	
	public List<PrdServiceItem> findPrdServiceItemByType(int typeId);
	/**最近发布的服务信息*/
	public List<PrdServiceItem> findPrdServiceItemByRecentN(int n);
	
	/**获取可用服务信息*/
	public Pager findServiceItemByAvailable(int typeId, int pageSize, int pageNo);
	
	/**获取未经审核的服务信息*/
	public Pager findUnauthorizedServiceInfo(int pageSize, int pageNo);
	
	/**按发布者查询*/
	public Pager findByPublisher(int contactId, int pageSize, int pageNo);
	
	public Pager findByAdmin(String title, String companyName, String typeName, 
			Date issuedDate,  Date expiredDate, Short isAuthenticated, int pageSize, int pageNo) ;
}
